### ISSUE TITLE
fix Pico SDK

### ISSUE THREAD

**Issue by Tyroonis** [Gothic-Unity-Project/Gothic-Unity#1]
After the fork, the Pico SDK no longer works.
Data was lost due to LFS.

FIX:
- create repo with pico OpenXR SDK
- add as dependency

![image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/d947aa85-8551-448a-ab0d-d4f2848b2c02)

**Comment by JaXt0r** [comment]
No problem. Let me add them to the [binary-dependencies](https://github.com/Gothic-UnZENity-Project/binary-dependencies) repository in a separate folder.

**Comment by JaXt0r** [comment]
I added the DLLs/SOs in https://github.com/Gothic-UnZENity-Project/binary-dependencies already.
The changes are in main of GUZ. Please check if it is working when you build for PicoVR.

Hints:
1. I added .so/.dll into gitignore. Whenever you update the Pico XR Plugin, you need to manually store the binaries into the binary-depencendy project to work.
2. I tried, but didn't make it to have all the Pico XR files (especially .cs scripts) to be used from package. Unity just didn't recognize the .cs files from package. Therefore I left the Assets/Plugin/Pico OpenXR/* files in this repository. (Makes updating the plugin a little bit more complex, but I couldn't get it to run properly, sorry.)
