### ISSUE TITLE
Loading performance: Disable Mesh + VOBs during loading

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#131]
## Description
When we currently load the game, all meshes of world and VOBs will be loaded fully and disabled once culling kicks in, which is _after_ everything is loaded. On VR devices loading starts to stutter more and more over time. Therefore let's disable all meshes/GOs once they're loaded immediately to save performance during loading.
![Image](https://github.com/user-attachments/assets/677b87ea-0d76-40c4-bc47-c7311480c231)

## Tasks
- [ ] World + VOBs - Once object is loaded, call .SetActive(false)
- [ ] Once everything is loaded and normal Culling kicks in (e.g. VobMeshCulling) we might need to do an initial .Query() to re-enable elements next to us. (Based on experience, culling won't trigger an initial "visible" Event)

**Comment by ThomasMountainborn** [comment]
We also need to remove the old texture arrays before starting to load the textures of the new world to avoid going out of memory on device.
