### ISSUE TITLE
LoadingScene isn't rendered when "NewGame" or "LoadGame" is clicked

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#33]
When we hit one of the two buttons, we should get a loading screen during load phase of the world. Currently we get no information, just a black screen while waiting for the world scene to become ready.

Hint: We get a warning which might indicate the issue.
![Image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/6970cf78-d790-4fe7-b144-1ebd05ebcccf)

**Comment by JucanAndreiDaniel** [comment]
I'll take this one as it bothered me when testing
