### ISSUE TITLE
Implement inventory - first iteration

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#46]
We need to have an inventory from a functional perspective (items are inside an inventory instance) and interaction wise (items can be pulled in and out of the inventory).

**Backend**
- [x] Implement basic Player Inventory class with a List of items in inventory
- [x] Once an item is grabbed and pulled out of the backpack, it needs to be removed from inventory and added to Voblist in game (for culling and saving)
- [x] vice versa when put into backpack

**UI**
- [x] if using HVR, leverage the existing backpack (for now) and draw items inside when pulled from shoulders (items have a mesh you just need to render it in the backpack slots)
- [x] putting items back into the backpack needs to "snap" them into the slots

**Out-of-scope:**
* A fully functional paging system for all the "thousands of objects we can have in inventory" is something for later
* We can think about another type of backpack later.
* Just use what we have right now to get a fine first skeleton for the whole experience.

**Comment by piotrb92** [comment]
@JaXt0r I have a lot of experience with inventories as I was mainly focusing on survival games for most of my 10+ years with Unity. Would love to take this on!

**Comment by JaXt0r** [comment]
Very much appreciated. Let's work on it together. I suggest you open a special-topic on Discord and a branch where I can provide the code snippets you need.

**Comment by JaXt0r** [comment]
This is solved for now as we implemented it for the modding workshop.
Let's team up for next iteration once you have time and interest, Piotr.
