### ISSUE TITLE
HVR: optimize item grabbing

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#49]
HvrGrabbable component is already attached to items, when HVR is active. But I didn't change any of the default parameters. Please let's have a look and optimize to some useful values.
(Hint: Previously tested in Lab scene)

**Comment by piotrb92** [comment]
Hi @JaXt0r, can you please provide more details on what is it you want to optimize? Happy to look into this.

**Comment by JaXt0r** [comment]
@piotrb92 fully flexible and up to you. I have no preference so far. I just thought about the 15+ parameters we can set inside the prefab component. Either you provide them with your values from your best practices. Or you quickly discuss it with us, what you would see as good options. Or you tell us: Default is great, and we keep it until someone complains. 😆

**Comment by piotrb92** [comment]
@JaXt0r default options are good, few things that will need to be configured per item is the weight of the rigidbody and the HVRSocketable component's "poses" that basically tell the sockets how to align the items when they are socketed.

**Comment by JaXt0r** [comment]
Hm. Ok. Your our expert in here. Can you please create separate tickets with the specific topics and we work on it once we're ready to do so (I think the topics like socketing is something we need to tackle later once we have the chests etc.?)
